config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root 'welcome#index'
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/dashboard', to: 'users#show'

  get '/playgrounds', to: 'playgrounds#index'
  get '/playgrounds/:id', to: 'playgrounds#show'
  post '/add_to_favorites', to: 'playgrounds/favorites#create'
  
  get '/playgrounds/:id/reviews/new', to: 'reviews#new' , as: :new_playground_review
  post '/playgrounds/:id/reviews', to: 'reviews#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @_current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    # require 'pry'; binding.pry
    @user = User.find(session[:user_id])
  end
end

app/controllers/playgrounds/favorites_controller.rb
class Playgrounds::FavoritesController < ApplicationController

  def create
    PlaygroundsService.new.add_favorite(favorite_data)
    redirect_to "/playgrounds/#{params[:playground_id]}"
    flash[:message] = 'This playground was added to your favorites'
  end

  private
    def favorite_data
      {
        user_id: params[:user_id],
        playground_id: params[:playground_id],
        playground_name: params[:playground_name]
      }
    end
end

app/controllers/playgrounds_controller.rb
# frozen_string_literal: true

class PlaygroundsController < ApplicationController
  def index
    if params[:location].present?
      @facade = PlaygroundsFacade.new(params[:location], params[:radius])
    else
      redirect_to root_path
      flash[:error] = 'Error: Must add location!'
    end
  end

  def show
    @facade = PlaygroundFacade.new(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    if current_user
    @playground_id = params[:id]
    else
      redirect_to "/playgrounds/#{params[:id]}", notice: 'You Must be Logged in to leave a Review'
    end
  end

  def create
    # AWS S3
    if params_present?(params)
      Aws.config.update(access_key_id: ENV['AWS_ACCESS_KEY'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
      bucket = Aws::S3::Resource.new.bucket(ENV['BUCKET_NAME'])
      file = bucket.object(params[:image].original_filename)
      file.upload_file(params[:image], acl: 'public-read')
      
      review_data = {
        user_id: params[:user_id],
        playground_id: params[:id],
        rating: params[:rating], 
        image: file.public_url,
        comment: params[:comment]
      }
      
      PlaygroundsService.new.add_review(review_data)
      redirect_to "/playgrounds/#{params[:id]}", notice: 'Review was successfully created.'
    else
      redirect_to new_playground_review_path(params[:id]), notice: 'All fields must be filled out.'
    end
  end
  

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :image)
  end

  def params_present?(params)
    params[:image].present? && params[:rating].present? && params[:comment].present?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    google_id = auth_hash['uid']
    name = auth_hash['info']['name']
    email = auth_hash['info']['email']
    token = auth_hash['credentials']['token']
    user = User.find_or_create_by(google_id:)
    user.update(name:, token:, email:)

    session[:user_id] = user.id
    redirect_to '/dashboard'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    if current_user
    @facade = FavoritesFacade.new(current_user.id)
    else
      redirect_to root_path
      flash[:error] = 'You must log in to visit this page'
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

<!-- JavaScript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>

    <title>PlayPalFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
     <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>PlayPal</title>
        <%= favicon_link_tag asset_path('Colorful Cute Rainbow Baby Clothes Logo.png') %>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
  </head>

<body id="page-top">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="#page-top">PlayPal</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="<%= root_path %>">Home</a></li>
                    <% if current_user %>
                        <li class="nav-item"><a class="nav-link" href="<%= dashboard_path %>">Dashboard</a></li>
                        <li class="nav-item-logout">
                            <%= button_to 'Logout', '/logout', method: :delete, class: 'nav-link-logout rounded', data: { confirm: 'Are you sure you want to logout?' } %>
                        </li>
                    <% else %>
                        <li class="nav-item">
                            <a class="nav-link" href="/auth/google_oauth2">Login With Google</a>
                        </li>
                    <% end %>
                </ul>
            </div>
        </nav>
    <%= yield %>
  </body>
 <!-- Footer-->
        <footer class="py-5 bg-black">
            <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; PlayPal 2023</p></div>
        </footer>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
</html>

app/views/playgrounds/index.html.erb
<header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                                    </div>
<h1 class="masthead-heading mb-0">Time to PlayPal</h1>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
<p><% @facade.playgrounds.each do |pg| %>
  <div id='pg-<%= pg.id %>'>
    <ul>
    <li>  <p><h4><%= link_to pg.name, "/playgrounds/#{pg.id}" %></h4>
      Address: <%= pg.address %></p>
      <p>Rating: <b><%= pg.rating%></b></p>
    </li>
    </ul>
    <br>
  </div>  
    <% end %>

app/views/playgrounds/show.html.erb
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-4">
                    <h1 class="masthead-heading mb-0"><%= @facade.playground_name %></h1><br>
                    <h3 class="masthead-subheading mb-0"><%= @facade.playground_address %>  <p><br>Rating: <%= @facade.playground_rating %></p></h3>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
<div id="image">
    <div class="row gx-3 align-items-center"><%= image_tag @facade.playground_image%></div>
</div>
<% flash.each do |type, message| %>
    <h4 class="error_msg"><%= message %></h4>
<% end %>
<% if current_user %>
  <%= form_with url: '/add_to_favorites', local: true do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :playground_id, value: @facade.id %>
  <%= f.hidden_field :playground_name, value: @facade.playground_name %>
  <div class='text-center'>
  <%= f.submit 'This Place Rules!', class: 'btn btn-primary btn-xl rounded-pill mt-5' %>
</div>
  <% end %>
<div class='text-center'>
<%= link_to "Add Your Two Cents!", new_playground_review_path(@facade.id), class: 'btn btn-primary btn-xl rounded-pill mt-5' %>
</div>
<% end %>
<br><br>
<div class='text-center'>
<h2 class='masthead-subheading'>Reviews:</h2>
</div>
 
<section>
<% @facade.reviews.each do |review| %>
  <div id='review_<%= review.id %>'>
        <div class="container px-5">
            <div class="row gx-5 align-items-center">
                <div class="col-lg-6">
                    <div class="p-5"><img class="img-fluid rounded-pill" src=<%= review.image %> alt="..." /></div>
                </div>
                <div class="col-lg-6">
                    <div class="p-5">
                        <h4 class="display-5"></b><%= review.user_name %> says...</h4>
                        <h4 class="display-6"><%= review.comment %></h4>
                        <h4 class="display-6"> Rating: <%= review.rating %></h4>
                    </div>
                </div>
            </div>
        </div>
  </div>
<% end %>
        </section>

app/views/reviews/new.html.erb
<header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                                    </div>
<h1 class="masthead-heading mb-0"> PlayPal Review</h1>
                    <br>
                    <%= form_with url: "/playgrounds/#{@playground_id}/reviews", method: :post, local: true do |f| %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                      <h4><%= f.label :rating, 'Rating:' %></h4>
                      <%= f.number_field :rating, in: 1..5, class: 'rounded-pill text-center number' %>
                      <br><br><br>
                      <h3> <%= f.label :comment, 'Review:' %></h3>
                      <%= f.text_area :comment, class: 'rounded', size: "50x5" %>
                      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
                      <main class="main_full">
                        <div class="container">
                          <div class="panel">
                            <div class="button_outer">
                              <div class="btn_upload">
                                <%= f.file_field :image, id: "upload_file", name: "image" %>
                                Upload Image
                              </div>
                              </div>
                          </div>
                        </div>
                      </main>
                      <% flash.each do |type, message| %>
                        <h4 class="error_msg"><%= message %></h4>
                      <% end %>
                      <%= f.submit "Tell 'em!", class: 'btn btn-primary btn-xl rounded-pill mt-5' %>
                    <% end %>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>

app/views/users/show.html.erb
<header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-5">
                                    </div>
<h1 class="masthead-heading mb-0"> Welcome to PlayPal, <%= current_user.name %></h1>
            <h3>Find a Playground Near Me</h3>
                    <br>
                    <%= form_with url: '/playgrounds', method: :get, local: true do |f| %>
                      <h6><%= f.label :location %></h6>
                      <%= f.text_field :location, class: 'rounded-pill' %>
                      <br><br>
                      <h6><%= f.label :radius, 'Search Mile Radius' %></h6>
                      <%= f.number_field :radius, class: 'rounded-pill', step: 0.5 %>
                      <br>
                      <%= f.submit 'Discover Playgrounds', class: 'btn btn-primary btn-xl rounded-pill mt-5' %>
                    <% end %>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>
        <br>
        <h1 class='text-center'> My Favorite Playgrounds </h1>
<p><% @facade.favorites.each do |favorite| %>
  <div id='pg-<%= favorite.playground_id %>'>
    <ul>
    <li>  <p><h4><%= link_to favorite.playground_name, "/playgrounds/#{favorite.playground_id}" %></h4>
    </li>
    </ul>
  </div>  
    <% end %>

app/views/welcome/index.html.erb
        <header class="masthead text-center text-white">
            <div class="masthead-content">
                <div class="container px-4">
                    <h1 class="masthead-heading mb-0">Welcome to PlayPal</h1>
                    <%= image_tag('Colorful Cute Rainbow Baby Clothes Logo.png') %>
                    <br><br><br><br>
                    <h3>Find a Playground Near Me</h3>
                    <br>
                    <%= form_with url: '/playgrounds', method: :get, local: true do |f| %>
                      <h6><%= f.label :location %></h6>
                      <%= f.text_field :location, class: 'rounded-pill' %>
                      <br><br>
                      <h6><%= f.label :radius, 'Search Mile Radius' %></h6>
                      <%= f.number_field :radius, class: 'rounded-pill', step: 0.5 %>
                      <br>
                      <% flash.each do |type, message| %>
                        <h4 class="error_msg"><%= message %></h4>
                      <% end %>
                      <%= f.submit 'Discover Playgrounds', class: 'btn btn-primary btn-xl rounded-pill mt-5' %>
                    <% end %>
                </div>
            </div>
            <div class="bg-circle-1 bg-circle"></div>
            <div class="bg-circle-2 bg-circle"></div>
            <div class="bg-circle-3 bg-circle"></div>
            <div class="bg-circle-4 bg-circle"></div>
        </header>